version: '1.0'

services:

  db_postgres:
    image: postgres:latest
    container_name: jp-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data:delegated
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres_db
    ports:
      - "5432:5432"
    networks:
      - service

networks:
  service:
    driver: bridge

volumes:
  postgres_data: